### ISSUE TITLE
Column subsetting error in blankODs

### ISSUE THREAD

**Issue by MadelaineB21** [JanEngelstaedter/grow96#3]
Hi Jan, when trying to run `processODData` I am getting this error:
`Blanking ODs ...Error: Can't subset columns that don't exist.`
`x Column '512' doesn't exist.`

This is my current code, with the directory set to the MIC_Assay folder in dropbox:
`RIF521 <- c(2^(9:1), 0)`
`processODData(specPath = "./specs/", `
`              dataPath = "./data/test/",`
`              blankGroups = RIF512)`

**Comment by JanEngelstaedter** [comment]
I think I have fixed this now. The problem was that the matrix with the data started in column 1 in the txt file but in column 2 in the xlsx file. Hopefully all kinds of files can now be handled by the processODData function.
